# Generated by Django 3.2.6 on 2022-04-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_given', models.IntegerField(default=0)),
                ('grade', models.IntegerField(default=0)),
                ('subject', models.CharField(default='', max_length=50)),
                ('comment', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('school', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=50)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
