# Generated by Django 3.2.6 on 2022-04-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherpage',
            name='teacher_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
