# Generated by Django 3.2.6 on 2022-04-14 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teacherpage_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherpage',
            name='teacher_id',
        ),
    ]
